### ISSUE TITLE
How about integrating this code genertor with psc-ide?

### ISSUE THREAD

**Issue by sudhirvkumar** [paf31/purescript-derive-lenses#13]
@paf31 @kRITZCREEK @nwolverson

How about we integrate this generator with psc-ide & editor plugins? so that we can access this functionality from within the editor? without having to jump to the command line?

**Comment by kritzcreek** [comment]
Since this just amounts to calling a shell script I'd prefer for this to be added to whatever editor plugin you're using instead of psc-ide. With Emacs for example it's trivial to set this up and if I find some time later I could show you how.

**Comment by sudhirvkumar** [comment]
@kRITZCREEK would love that... thanks a ton!

**Comment by sudhirvkumar** [comment]
@kRITZCREEK thinking a bit more about it...

If it was part of psc-ide... then we will have access to AST and we will be able to selectively generate lenses for the type under the cursor. Just like we do the `apply suggestion`... what is your thought on that?

**Comment by kritzcreek** [comment]
I think that should happen through either Template PureScript https://github.com/purescript/purescript/issues/140

or a plugin system for psc-ide, but I wouldn't want to special case Profunctor Lenses in the compiler repo just for convenience.

**Comment by sudhirvkumar** [comment]
@kRITZCREEK plugin system for psc-ide sounds great... Is there any plan for a plugin system?

**Comment by nwolverson** [comment]
I guess any editor should have capability to fire off a command on the current buffer, but maybe there's a place for a standard code generation/preprocess hook somewhere

**Comment by paf31** [comment]
I agree that this should be accomplished using editor key bindings, or one day, possibly Template PureScript.

**Comment by sudhirvkumar** [comment]
@paf31 Template PureScript sounds good... I am not a big fan of Template Haskell mainly because... I am not sure what code will be generated behind the scenes...

What if... we can write Template PureScript and psc-ide generates the code and then comments out the Template PureScript!

I would prefer seeing the code and using Template PureScript as a helper during development!

Thanks for your time.
