### ISSUE TITLE
Type support

### ISSUE THREAD

**Issue by user471** [paf31/purescript-derive-lenses#6]
Is it possible to generate lenses for

```
type Foo = {foo :: Int}
```

?

**Comment by paf31** [comment]
Yes, shouldn't be difficult.

**Comment by pkamenarsky** [comment]
Is there a problem with merging this?

**Comment by paf31** [comment]
Not necessarily, it's on my list and I'll get round to it soon.

**Comment by pkamenarsky** [comment]
Perfect, thank you!
